package decks

// Brasil: a zoeira que só faz sentido aqui -- futebol, fila, imposto,
// tio de WhatsApp, réveillon, festa junina e a certeza de que o país
// é um dos maiores do mundo de qualquer jeito.
func init() {
	Register(Deck{
		ID:          "brasil",
		Name:        "Brasil",
		Emoji:       "🇧🇷",
		Description: "Futebol, fila, imposto e tio de WhatsApp. Zoeira que só faz sentido aqui.",
		whites: []string{
			"A CPI que não descobre nada",
			"O laudo do IML",
			"Açaí de dois litros com whey",
			"O tio que sabe o motivo de todo problema do país",
			"Um gol no último minuto",
			"O pênalti mal marcado",
			"A narração que grita 'GOOOOL' por quarenta segundos",
			"Um pastel de feira com ovo de codorna",
			"O puxador de prosa da barbearia",
			"Um eleitor de cada lado dividindo o mesmo táxi",
			"A fila do INSS",
			"O condomínio de fachada 'planejada'",
			"Um vaqueiro de moto na estrada de terra",
			"O cambista na porta do estádio",
			"Cerveja de garrafa servida no copo de plástico",
			"O caipirão do bar do Zé",
			"Uma moto com três capacetes",
			"O sinal vermelho com três vendedores",
			"Um cachorro-quente de rua com purê em cima",
			"A chuva que estragou o réveillon na praia",
			"O bloco de carnaval do bairro",
			"Um sambista madrugador",
			"O 'só a brisa' na balada",
			"Um carro de som de campanha",
			"O santinho no para-brisa",
			"O foguetório da festa junina às 5h",
			"Um tucano e um papagaio discutindo no bar",
			"O 'amanhã eu pago' do vizinho",
			"Uma troca de figurinhas da Copa",
			"O galo caramelo da comunidade",
			"O bingão do clube de mães",
			"Uma salada de frutas com leite condensado",
			"O sacolão da esquina",
			"A van da escola tocando forró",
			"Um imposto sobre o próprio imposto",
			"O PIX do golpe do falso 'tio'",
			"O áudio do grupo 'só quem é de confiança'",
			"A marmita de domingo no bar do bairro",
			"Um jogo do Brasil às 3h da tarde numa quarta-feira",
			"O 'vai ter que ir no bolo do meu filho'",
			"O banho de balde no dia de falta d'água",
			"Uma vela acesa para o casamento da filha",
			"O churrasqueiro que só tem sal e pimenta",
			"Um pacote de biscoito de polvilho",
			"A renda extra do MEI fantasma",
			"O 'vai ter obra mesmo assim'",
			"Um laudo do DETRAN de outro estado",
			"A feijoada que rende até terça",
			"O parabéns pra você cantado errado de propósito",
			"Uma bicicleta com fita adesiva segurando o guidão",
		},
		blacks: []string{
			"O Brasil é o único país onde _.",
			"Em 2050, o hino nacional vai citar _.",
			"O que não pode faltar num churrasco de verdade? _.",
			"A Copa de 2030 será decidida por _.",
			"Nada é tão brasileiro quanto _.",
			"O novo imposto vai incidir sobre _.",
			"A novela das nove vai terminar com _ casando com _.",
			"O que fez o ônibus atrasar dessa vez? _.",
			"O segredo do melhor açaí da cidade é _.",
			"A CPI das CPIs concluiu que _.",
			"O que meu tio mandou no grupo da família hoje? _.",
			"O réveillon da praia vai ter _ no palco principal.",
			"Sexta-feira, 18h, na marginal: _ e _.",
			"O que resolve o problema do país mas ninguém usa? _.",
			"A primeira lei do novo governo: _.",
			"O que o cambista grita na porta do estádio? '_!'",
		},
	})
}