
package decks

// generated content, committed verbatim -- run scripts/gen via the
// repo history if it ever needs regenerating
func init() {
	Register(Deck{
		ID: "cah",
		Name: "CAH: Edi\u00e7\u00e3o Brasileira",
		Emoji: "🃏",
		Description: "O set original real: o absurdo cl\u00e1ssico na adapta\u00e7\u00e3o brasileira. 18+.",
		whites: []string{
			"Abortos com cabide",
			"Carne humana",
			"Autocanibalismo",
			"M\u00e3os de Jazz vigorosas",
			"P\u00e1ssaros que n\u00e3o voam",
			"Fotos de peitos",
			"A coisa certa a se fazer",
			"Acidentes de ca\u00e7a",
			"Um camelo cartunesco apreciando o suave e refrescante gosto de um cigarro",
			"A viola\u00e7\u00e3o dos nossos direitos humanos fundamentais",
			"Viagra",
			"Autoavers\u00e3o",
			"Um abd\u00f4men espetacular",
			"Um policial honesto com nada a perder",
			"Abstin\u00eancia",
			"Um caf\u00e9 da manh\u00e3 balanceado",
			"Red Bull",
			"O ato de esconder uma ere\u00e7\u00e3o",
			"Sedativos",
			"Faust\u00e3o convulsivamente vomitando enquanto uma ninhada de aranhas-caranguejo eclodem em seu c\u00e9rebro e irrompem de seus ductos lacrimais",
			"O ato de tuitar",
			"O Big Bang",
			"Pessoas com membros amputados",
			"Zumbi dos Palmares",
			"Ex-presidente Lula",
			"Marginalizado",
			"Smegma",
			"O ato de botar um ovo",
			"Carinho",
			"M\u00e9dici costurando casaquinhos de l\u00e3 para c\u00e3es de rua",
			"O papa",
			"Um cu alvejado",
			"Carne de cavalo",
			"Piercings genitais",
			"Dedadas",
			"Asi\u00e1ticos idosos",
			"Perigo estranho",
			"O pr\u00f3prio medo",
			"Ci\u00eancia",
			"Cura Gay",
			"Patina\u00e7\u00e3o de casais do mesmo sexo",
			"Os terroristas",
			"Sexo com ela",
			"Pornochanchada",
			"Bulimia",
			"Apagamento de etnias",
			"Trapa\u00e7a nas paraolimp\u00edadas",
			"Restart",
			"Heteronormatividade",
			"Regina Cas\u00e9",
			"Biquinho",
			"Motosserras como m\u00e3os",
			"Placenta",
			"Ant\u00f4nio Fagundes voando num boi feito de raios",
			"In\u00eas Brasil",
			"FADAS!",
			"Lobotomia com picador de gelo",
			"Thais Ara\u00fajo",
			"Inje\u00e7\u00f5es de horm\u00f4nios",
			"Um Urubu com chap\u00e9u de palha",
			"Prep\u00facio",
			"Morte",
			"Dubl\u00eas",
			"A m\u00e3o invis\u00edvel",
			"Plugs anais",
			"Um chap\u00e9u muito maneiro",
			"Enchentes",
			"Camisinhas saborizadas",
			"Morte por disenteria",
			"Lutas de travesseiros sexy",
			"Tratado de Tordesilhas",
			"Uma punheta triste",
			"Homens",
			"Exclus\u00e3o social",
			"Pitty",
			"Orf\u00e3os apaixonantes",
			"Surf",
			"O clit\u00f3ris",
			"Cangaceiros",
			"Amigos que comem o lanche todo",
			"O metr\u00f4",
			"Fingir que se importa",
			"Ataques de dinossauros",
			"Um microp\u00eanis",
			"Uma maldi\u00e7\u00e3o ind\u00edgena",
			"Agricultura",
			"J\u00f3ias",
			"Uma co\u00e7ada clandestina na bunda",
			"O sul",
			"Cheirar cola",
			"Contatinhos",
			"Meus quadris",
			"Gansos",
			"Babaquice com crian\u00e7as",
			"Estraga prazeres",
			"Luz do sol e arco-iris",
			"PARA NOSSA ALEGRIA!",
			"Destrui\u00e7\u00e3o mutuamente assegurada",
			"Os pelos do peito de Tony Ramos",
			"Sexting",
			"Complexo de Edipo",
			"AAAAAAAAAAAAAAAAAAAAAAAAAA",
			"Um festival de salsicha",
			"Roberto Carlos",
			"A Cuca",
			"Cavalheirismo",
			"Compartilhar de seringas",
			"Riqueza",
			"Tapado",
			"O Le\u00e3o do Proerd",
			"Combust\u00e3o espont\u00e2nea",
			"Faculdade",
			"Necrofilia",
			"A sele\u00e7\u00e3o chinesa de gin\u00e1stica",
			"Aquecimento global",
			"Peidar e sair de fininho",
			"O Mau correndo pelos encanamentos da Assembl\u00e9ia de Deus",
			"Um galo com papete",
			"Inveja peniana",
			"Liberdade pessoal",
			"Gente branca",
			"Eduardo Cunha",
			"Um voicemail bizarro",
			"Fermento",
			"Sele\u00e7\u00e3o natural",
			"Masturba\u00e7\u00e3o",
			"Bolinhos Bauducco",
			"Festa junina",
			"Polegares opositores",
			"Um capuccino grande, sem a\u00e7\u00facar, gelado e com caramelo de soja",
			"Sujar-se",
			"Uma mulher negra audaciosa",
			"Lontras com meias de bolinhas e nariz de palha\u00e7o",
			"O ensino de emo\u00e7\u00f5es a um rob\u00f4",
			"A Rita Lee vestida de banana",
			"Um tiroteio",
			"Chicoteio",
			"Sexo de pandas",
			"Catapultas",
			"L\u00e1zaro Ramos",
			"O p\u00eanis do Alexandre Pires",
			"32 cm",
			"Minas terrestres",
			"Um mar de problemas",
			"Acaraj\u00e9 no caf\u00e9 da manh\u00e3",
			"Nazar\u00e9 Tedesco segurando uma tesoura",
			"Fric\u00e7\u00e3o",
			"Bolas",
			"AIDS",
			"O KKK",
			"Pudim",
			"Seppuku",
			"\u00c9 o Tchan",
			"Gandhi",
			"Paralamas do Sucesso",
			"Preadolescentes",
			"A minoria simb\u00f3lica",
			"Amigos com benef\u00edcios",
			"Presentes",
			"Bukkake pixelado",
			"Professores substitutos",
			"Treta",
			"Uma detona\u00e7\u00e3o termonuclear",
			"Sono durante uma aula chata",
			"#EuEscolhiEsperar",
			"Um cavalinho",
			"Vergonha na cara",
			"C\u00e1ries dentais",
			"Pastel de queijo e caldo de cana",
			"Cheiro de gente velha",
			"Lampi\u00e3o",
			"Cozinha mexicana aut\u00eantica",
			"Pirulitos gigantes",
			"Louro Jos\u00e9",
			"Palmirinha vestida de paquita",
			"Mulheres fortes",
			"Interven\u00e7\u00e3o Militar",
			"Topless",
			"Meritocracia",
			"Bacteria comedora de carne",
			"Abuso infantil",
			"Um freezer cheio de \u00f3rg\u00e3os",
			"Um momento de sil\u00eancio",
			"Sandy e Junior",
			"Sonhos er\u00f3ticos com o Abaporu",
			"Robocop",
			"Aquele teletubbie gay",
			"Doce, doce vingan\u00e7a",
			"Banquete chique",
			"Uma colonoscopia com suas pr\u00f3prias fezes todos os dias",
			"O chupacu",
			"Fraternidades judias",
			"Roupa \u00edntima comest\u00edvel",
			"Gente pobre",
			"Rod\u00edzio de pizza por dez reais",
			"Anitta aos 65 anos",
			"Aquela coisa que eletrocutou seu abd\u00f4men",
			"A insensatez humana",
			"Bosta ardente",
			"Cards Against Humanity",
			"Um assassinato muito cruel",
			"Tempo pra mim",
			"A morte inevit\u00e1vel do universo",
			"Emiss\u00f5es noturnas",
			"Problemas com pai",
			"Os m\u00e9dicos cubanos",
			"Bruna Marquezine",
			"Sexo no banheiro do Mc Donalds",
			"Laminas de mamilos",
			"Cal\u00e7as sem bunda",
			"Nudez frontal completa",
			"Kleber Bambam",
			"Passiva-agressividade",
			"Dilma Rousseff",
			"Atropelamento",
			"Menstrua\u00e7\u00e3o",
			"Coito interrompido",
			"Garotas em cl\u00ednicas de aborto",
			"Ditadura Gay",
			"A Biblia Sagrada",
			"Paz mundial",
			"Morte aos seus inimigos esmagados por um candelabro",
			"Tor\u00e7\u00e3o testicular",
			"O leiteiro",
			"Um paradoxo temporal",
			"Hot Pockets",
			"Caras que n\u00e3o ligam",
			"Churrasco de mico-le\u00e3o-dourado",
			"Darth Vader",
			"Conex\u00e3o humana genu\u00edna",
			"Sem-Teto",
			"O cu imaculado de Eliana",
			"Gloryholes",
			"Solos de saxofone",
			"A arte da sedu\u00e7\u00e3o",
			"Deus",
			"Design inteligente",
			"Um sistema de classes impregnado",
			"Fogo amigo",
			"Emo\u00e7\u00f5es",
			"Eugenia",
			"Uma boa cheirada",
			"Uma bola de cera de ouvido, semen e peda\u00e7os de unha",
			"Um tamagotchi rejeitado",
			"Estupidez imensur\u00e1vel",
			"Migalhas espalhadas por todo o maldito tapete",
			"O cora\u00e7\u00e3o de uma crian\u00e7a",
			"Sedu\u00e7\u00e3o",
			"O gosto refrescante e geladinho do Guaran\u00e1 Antartica",
			"O cu delicioso do Caio Castro",
			"Uma surpresa salgada",
			"Piadas sobre o Holocausto em uma hora ruim",
			"Minha alma",
			"Minha vida sexual",
			"Ovos de pterodactilos",
			"Seu Coiso, Coisa e Coisinha (ilha Ra-Tim-Bum)",
			"Qualquer coisa que saia da boca de Rachel Sheherazade",
			"72 virgens",
			"Epidemia de var\u00edola",
			"Um tapa merecido",
			"Uma tartaruga mordendo a ponta do seu p\u00eanis",
			"Uma vaca louca",
			"Um pum engra\u00e7ado",
			"Minha cole\u00e7\u00e3o de objetos sexuais high-tech",
			"Um homem de meia idade de patins",
			"O sangue de Cristo",
			"Preliminares meia-boca",
			"Amostras gr\u00e1tis",
			"Babacas em seus Iphones",
			"Stalin",
			"12 GB de gifs da Gretchen em HD",
			"Coxinhas",
			"O teto de vidro",
			"Uma boca suja",
			"Divers\u00e3o em uma piscina de l\u00e1grimas de crian\u00e7as",
			"Frita\u00e7\u00e3o",
			"Os deformados",
			"Os bra\u00e7os de Marcela Temer",
			"Explos\u00f5es",
			"Dandara dos Palmares",
			"Michel Temer",
			"Bolsonaro",
			"Atitude",
			"Essa resposta \u00e9 p\u00f3s-moderna",
			"Capitalismo",
			"Morte por falta de ar perto do nariz do Luciano Huck",
			"Exerc\u00edcios de constru\u00e7\u00e3o de times",
			"Repress\u00e3o",
			"Comunismo",
			"Uma bolsa de feij\u00f5es m\u00e1gicos",
			"Uma espanhola assim\u00e9trica",
			"Pais mortos",
			"Ridiculariza\u00e7\u00e3o em p\u00fablico",
			"Exibi\u00e7\u00e3o de acasalamento",
			"Um m\u00edmico tendo um AVC",
			"Stephen Hawking falando safadezas",
			"Criancas africanas",
			"Herpes bucal",
			"Uma vov\u00f3 pelada",
			"Destrui\u00e7\u00e3o da evid\u00eancia",
			"Putas",
			"Italianos",
			"Um milh\u00e3o de reais em barras de ouro, que valem mais do que dinheiro",
			"Um moinho de vento cheio de cad\u00e1veres",
			"Sua alteza, rainha Elizabeth II",
			"Exatamente o que voc\u00ea esperava",
			"Uma corrente intermin\u00e1vel de diarr\u00e9ia",
			"Problemas de classe m\u00e9dia",
			"Torrada",
			"Uma camisinha defeituosa",
			"Doa\u00e7\u00e3o de pedra do rim",
			"Lepra",
			"Um tumor cerebral",
			"Abelhas?",
			"Cachorrinhos!",
			"Brigas de galo",
			"Sangue, fadiga, l\u00e1grimas e suor",
			"Esperan\u00e7a",
			"Cu no lugar dos olhos",
			"Incesto",
			"Roubo de t\u00famulo",
			"Alcoolismo",
			"Disfun\u00e7\u00e3o er\u00e9til",
			"Felipe Dylon",
			"Bestialidade",
			"Crushes",
			"Testemunhas de Jeov\u00e1",
			"Crian\u00e7as com c\u00e2ncer de bunda",
			"Tr\u00eas pintos ao mesmo tempo",
			"Sopa quente demais",
			"Yodeleio inapropriado",
			"Bomba de horm\u00f4nios",
			"Uma AK-47",
			"Uma cara feia",
			"Uma vagina com joias",
			"A ira de Vladimir Putin",
			"O pr\u00f3prio dem\u00f4nio",
			"Meu status de relacionamento",
			"Uma maldita paz e quietude",
			"Fabulosidade",
			"Lactacao",
			"Sexo oral n\u00e3o-reciproco",
			"Minha ex",
			"Meus genitais",
			"Uma vagina cibern\u00e9tica que faz torrada e tem wifi",
			"Orgasmo feminino",
			"Um irland\u00eas s\u00f3brio que n\u00e3o se importa com batatas",
			"Reabilita\u00e7\u00e3o por ordem judicial",
			"O parto do anticristo",
			"Os gays",
			"Ecstasy",
			"Estrogenio",
			"Brutalidade policial",
			"Pessoas sem pele",
			"Um homem quase gozando",
			"Dedos em formato de penis",
			"Racismo",
			"Racismo reverso",
			"Sexo surpresa!",
			"Sutilezas classistas",
			"Os tweets do Neymar Jr",
			"Musicas atuais",
			"Seu irm\u00e3o estranho",
			"Uma vida de tristezas",
			"Cal\u00e7as extremamente apertadas",
			"Fraldas sujas",
			"Casamento, procria\u00e7\u00e3o, seguida de fotos, aposentadoria e morte",
			"Porn\u00f4 de tentaculos",
			"O boi tat\u00e1",
			"Muito gel de cabelo",
			"C\u00e9lulas-tronco embrion\u00e1rias",
			"For\u00e7as misteriosas fora do nosso controle",
			"Ira menstrual",
			"Os ritmos africanos",
			"Acidentes horr\u00edveis de depila\u00e7\u00e3o a laser",
			"Objetos brilhantes",
			"Golden showers",
			"Meus dem\u00f4nios interiores",
			"Roubo de doces de crian\u00e7as \u00f3rf\u00e3s",
			"Um homem branco numa van",
			"Gravidez na adolesc\u00eancia",
			"Nazistas",
			"Privil\u00e9gio branco",
			"Uma ere\u00e7\u00e3o que dura mais de quatro horas",
			"Uma festa de aniversario desapontadora",
			"Puberdade",
			"Dois an\u00f5es cagando num balde",
			"Deveres de esposa",
			"O fruto proibido",
			"Raul Gil alisando a pr\u00f3pria barriga at\u00e9 dormir",
			"Tens\u00e3o sexual",
			"A separa\u00e7\u00e3o do Calypso",
			"Um ant\u00edlope com gases",
			"Aquelas vezes que voce fica com areia na sua vagina",
			"Um louco que vive numa caixa e sequestra mulheres",
			"Tartarugas de assalto com bafo \u00e1cido biologicamente modificadas",
			"O fim dos dias",
			"Estrelas porn\u00f4",
			"Um feto",
			"Obesidade",
			"Quando voce peida e um pouquinho sai",
			"Oompa-Loompas",
			"BATMAN!!!",
			"Gente negra",
			"A luz de um bilh\u00e3o de s\u00f3is",
			"Gente gostosa",
			"Vov\u00f3",
			"Sacrif\u00edcio de uma virgem",
			"Fome",
			"Pintura a dedo",
			"O milagre do nascimento",
			"Cabras comendo latas",
			"Um macaco fumando",
			"Cura pela f\u00e9",
			"Sexo menstrual",
			"Beb\u00eas mortos",
			"Evang\u00e9licos ultraconservadores",
			"Impot\u00eancia",
			"Concursos de beleza infantis",
			"Centauros",
			"Desodorante AXE",
			"Wesley Safad\u00e3o",
			"O direito a voto feminino",
			"Crian\u00e7as com coleiras",
			"A dan\u00e7a da fada da ameixa doce",
			"O dedo perdido do Lula",
			"Arremesso de an\u00f5es",
			"Pessoas de exatas",
			"Almo\u00e7o",
			"Mulheres em comerciais de iogurte",
			"Fernandinho Beira-Mar",
			"Coxas poderosas",
			"O Dollynho, bem atr\u00e1s de voc\u00ea",
			"Ferimentos de facadas m\u00faltiplos",
			"Melhorias cibern\u00e9ticas",
			"Servid\u00e3o",
			"Outro maldito filme de vampiro",
			"A Ana Maria Braga dan\u00e7ando Ragatanga de biquini fio-dental de estampa de oncinha",
			"Uma grande como\u00e7\u00e3o por motivo nenhum",
			"Um pouquinho de mijo",
			"A agita\u00e7\u00e3o",
			"Fantasmas",
			"Bananas de Pijamas",
			"Escuta ativa",
			"V\u00f4mito de ar",
			"Pilotos kamikaze",
			"A For\u00e7a",
			"Vibradores azuis",
			"Crian\u00e7a Esperan\u00e7a",
			"Pessoas de Humanas",
			"Aplausos ao sol",
			"Heterossexuais",
			"Rebuceteio",
			"P\u00e9ssimas escolhas de vida",
			"Pessoas pobres",
			"Pessoas ricas",
			"Minha vagina",
			"Personagens femininas fortes",
			"Sexo consensual",
			"Um balde de cabe\u00e7as de peixes",
			"Um cora\u00e7\u00e3o de uma crian\u00e7a",
			"A vida de um pirata",
			"Crucifica\u00e7\u00e3o",
			"Cinco litros de cacha\u00e7a",
			"O ursinho Pooh possu\u00eddo pelo dem\u00f4nio",
			"Um bangal\u00f4 na praia",
			"Uma capivara beb\u00ea usando pantufinhas e pijaminha azul",
			"Empregos",
			"400 anos de atrocidades coloniais",
			"Pessoas ind\u00edgenas",
			"Uma bela x\u00edcara de caf\u00e9",
			"Uma tribo de mulheres guerreiras",
			"A rolezeira",
			"Memes",
			"Trenzinho Carreta Furac\u00e3o",
			"Silvio Santos jogando dez avi\u00f5ezinhos de 100 reais",
			"Uma manchete de not\u00edcia do Ego",
			"As bailarinas do Faust\u00e3o",
			"A Maisa tirando a peruca do Silvio Santos",
			"A Gl\u00f3ria Maria doidona na Jamaica",
			"Apropria\u00e7\u00e3o cultural",
			"Um cachorro quente de rua com recheio de proced\u00eancia duvid\u00e1vel",
		},
		blacks: []string{
			"_ ? Tem um aplicativo para isso.",
			"Eu tenho 99 problemas mas _ n\u00e3o \u00e9 um.",
			"Antrop\u00f3logos recentemente descobriram uma antiga tribo que venerava _",
			"\u00c9 uma pena que crian\u00e7as hoje em dia estejam todas se envolvendo com _",
			"Durante o Per\u00edodo Marrom de Picasso ele pintou centenas de quadros de _",
			"A medicina alternativa est\u00e1 adotando os poderes curativos de _",
			"O \u00d3scar de _ vai para _",
			"A nova temporada de A Fazenda apresenta 17 celebridades falidas convivendo com _",
			"Eu bebo para esquecer _",
			"Desculpe, professor, n\u00e3o consegui terminar minha tarefa de casa por causa de_",
			"\u00c9 assim que o mundo acaba: n\u00e3o com uma explos\u00e3o, mas com _",
			"As novas regras de seguranca agora pro\u00edbem _ em avi\u00f5es.",
			"_. \u00c9 assim que eu morro.",
			"Para meu pr\u00f3ximo truque, eu vou tirar _ de _",
			"No novo filme da Xuxa, ela precisa lidar com _ pela primeira vez",
			"_ , uma porta de entrada para _",
			"Queria n\u00e3o ter perdido o manual de _.",
			"Ao inv\u00e9s de carv\u00e3o, agora o Papai Noel d\u00e1 _ para crian\u00e7as mal comportadas.",
			"Em 1000 anos, quando dinheiro impresso for uma mem\u00f3ria distante, _ vai ser a moeda de troca.",
			"No novo epis\u00f3dio de Black Mirror, Wagner Moura descobre que _ era, na verdade, _ o tempo todo.",
			"Um jantar rom\u00e2ntico \u00e0 luz de velas estaria incompleto sem _.",
			"_ . Aposto que voc\u00ea n\u00e3o consegue ficar sem repetir!",
			"Gente branca gosta de _.",
			"_. Toca aqui, mano!",
			"O pr\u00f3ximo livro de J.K Rowling : Harry Potter e _.",
			"A TOPTHERM TRAZ PRA VOC\u00ca O LEG\u00cdTIMO _.",
			"Num mundo devastado por _, nosso \u00fanico consolo \u00e9 _.",
			"Durante o sexo eu gosto de pensar em _.",
			"Quando eu estiver na pris\u00e3o, eu vou contrabandear _ .",
			"_. \u00c9 uma cilada, Bino!",
			"Nos teatros mais pr\u00f3ximos, _: O musical.",
			"Enquanto os EUA e a URSS faziam a corrida espacial, o governo brasileiro gastou milh\u00f5es de reais pesquisando _",
			"Ap\u00f3s os desastres de Mariana, Claudia Raia comprou _ para o povo mineiro.",
			"Depois de um fiasco no setor de relacoes publicas, o Carrefour nao oferta mais _",
			"Em sua nova com\u00e9dia de ver\u00e3o, Renato Arag\u00e3o \u00e9 _ preso no corpo de _",
			"Os rumores dizem que o prato predileto de Dilma Rousseff \u00e9 _ cheio de _",
			"Mas antes de mat\u00e1-lo, Sr. Bond, preciso te mostrar _",
			"A viagem de campo foi arruinada por _",
			"Quando o Fara\u00f3 estava im\u00f3vel, Mois\u00e9s chamou pela Praga de _",
			"Eu nunca entendi verdadeiramente _ at\u00e9 encontrar _",
			"A Pol\u00edcia Militar comecou a enviar _ para as crian\u00e7as em M\u00e3e Luiza.",
			"_ : Bom at\u00e9 a \u00faltima gota.",
			"_ : Testado por crian\u00e7as, aprovado pelas m\u00e3es.",
			"Estudos mostram que ratos de laborat\u00f3rio atravessam labirintos 50% mais r\u00e1pido depois de expostos a _",
			"A vida era dif\u00edcil para os homens das cavernas antes de _",
			"Escreva um haiku sobre _.",
			"Eu n\u00e3o sei que armas vao usar na terceira guerra mundial, mas na quarta usar\u00e3o _",
			"Nos ultimos momentos de Raul Seixas, ele pensou sobre _",
			"Numa tentativa de obter maior audi\u00eancia, o Museu C\u00e2mara Cascudo oferecer\u00e1 uma exibi\u00e7\u00e3o interativa de _",
			"Quando eu for presidente da rep\u00fablica, vou criar o minist\u00e9rio de _",
			"A sess\u00e3o da tarde apresenta: _, uma hist\u00f3ria de _",
			"Quando eu for um bilion\u00e1rio, vou erguer uma est\u00e1tua de 20 metros em homenagem a _",
			"Quando eu estava viajando com LSD, _ virou _",
			"Verdade, eu matei _ . Como? _",
			"_ + _ = _",
			"A FIFA baniu _ por dar aos jogadores uma enorme vantagem",
			"Talvez ela tenha nascido assim, talvez seja _",
			"Eu consigo seguir em frente com uma pequena ajuda de _",
			"Querida tia Tereza, estou tendo um problema com _ e gostaria da sua ajuda.",
			"Mais uma noite chega, e com ela _",
			"Disseram que n\u00f3s \u00e9ramos loucos, disseram que n\u00e3o poder\u00edamos colocar _ dentro de _. Eles estavam errados.",
			"Aqui tamb\u00e9m \u00e9 _",
			"Olha como ela \u00e9 _, d\u00e1 _ pra ela !",
			"\"O tema para o pr\u00f3ximo Quem Sabe Canta, do Raul Gil, ser\u00e1 \"N\u00f3s somos _\"\"",
			"Ningu\u00e9m espera a revolu\u00e7\u00e3o comunista, nossas principais armas s\u00e3o medo, surpresa e _",
			"A TAM pede desculpas pelo atraso dos voos devido a _",
			"A seguir, em Esporte Espetacular, o Campeonato Mundial de _",
			"\"Hoje, em Casos de Fam\u00edlia: \"Socorro! Meu filho \u00e9 _ !\"\"",
			"A vida dos povos ind\u00edgenas no Brasil mudou para sempre quando o homem branco os introduziu a _",
			"Dica divertida! Quando o seu homem pedir para voc\u00ea fazer um oral, surpreenda-o com _, no lugar",
			"\"Hoje, na Sess\u00e3o da Tarde: \"_, a hist\u00f3ria de _\" (2)\"",
			"_. \u00c9 por isso que as m\u00e3es v\u00e3o para o Acre",
			"Eu n\u00e3o acredito que _ inventou _",
			"A nova sensa\u00e7\u00e3o do Funk \u00e9 o Mc _",
			"O Yudi girou a roleta do Bom Dia e Cia, e ao inv\u00e9s de vir um play station, veio _",
			"Beijinho no ombro pra _ passar longe",
			"Tu t\u00e1 metida com _, Morena ?",
			"Ap\u00f3s a \u00c9poca do Caf\u00e9, o Brasil investiu na exporta\u00e7\u00e3o de _",
			"Casar, foder, matar: _, _ e _.",
		},
	})
}
