package decks

// O Clássico: o mix padrão, no espírito do jogo original -- o
// cotidiano, o nojento e o absurdo se misturando. Nem leve, nem
// pesado: o deck "qualquer churrasco" do cch.
func init() {
	Register(Deck{
		ID:          "classico",
		Name:        "Clássico",
		Emoji:       "🃏",
		Description: "O mix padrão: cotidiano, nojeira e absurdo. Bom pra qualquer roda.",
		whites: []string{
			"Um bebê chorando no voo",
			"O cheiro de churrasco na roupa",
			"Uma piada de mau gosto contada no velório",
			"Um grupo de WhatsApp da família",
			"O áudio de sete minutos no grupo",
			"Cabelo entupindo o ralo",
			"Fritura em óleo reutilizado desde 2015",
			"Um assalto à mão armada",
			"A fila do SUS",
			"Uma tatuagem do nome do ex",
			"Coentro",
			"Um churrasco com salsicha vencida",
			"Pelos no sabonete",
			"A segunda cerveja",
			"Um bicho de estimação abandonado",
			"Uma cobra no vaso sanitário",
			"A aposentadoria do meu tio",
			"Falar alto no celular no ônibus",
			"Um sorvete derretido no bolso",
			"Um espelho embaçado de academia",
			"O cheiro do ônibus lotado às 18h",
			"Cortar a fila do aeroporto",
			"Um dente doendo desde 2019",
			"O vizinho que começa obra às 7h",
			"Uma aliança perdida no fundo do mar",
			"Fazer xixi na piscina",
			"O caldo de cana do camelô",
			"Um pastel de vento",
			"A fatura do cartão de crédito",
			"Uma mensagem de voz bêbada",
			"Um gato de rua com opinião",
			"Uma calça rasgada no lugar errado",
			"Fingir que entendeu a piada",
			"Uma feira livre às 6h de domingo",
			"Um pneu careca na estrada",
			"Uma piada interna que ninguém explicou",
			"O ar-condicionado quebrado em janeiro",
			"Uma selfie com flash no espelho",
			"Um joelho raspado na calçada",
			"Um sanduíche de mortadela da cantina",
			"Uma resposta 'kkk' seca",
			"Sexo oral",
			"Vômito de festa",
			"Suor noturno",
			"A Ditadura Militar",
			"Uma crônica de cistite",
			"O 'eu avisei' da sogra",
			"Um pedaço de osso no espetinho",
			"A última fatia de pizza disputada",
			"Uma crachá de estagiário",
			"O 'vamos marcar' que nunca acontece",
			"Um atestado médico suspeito",
			"O calçado de borracha do meu avô",
			"Uma toalha de mesa cheia de formiga",
			"O 'depois eu faço dieta'",
			"Uma penteadeira cheia de amostra grátis",
			"O 'só cinco minutinhos' do chefe",
			"Um cachorro caramelo sorrindo",
			"Uma crônica da ressaca de segunda",
			"O balde de limpeza do pedágio",
			"Uma conversa de elevador com vizinho",
			"O 'acabou o papel' no banheiro da empresa",
			"Um piercing no lugar errado",
			"A fila do banco no dia de pagamento",
			"Uma vela aromática de 'pão de queijo'",
			"O cheiro de cigarro do vizinho entrando pela janela",
			"Uma conta de luz suspeita",
			"O 'confia' do corretor de imóveis",
			"Um idoso dirigindo no meio do caminho",
			"__",
			"__",
		},
		blacks: []string{
			"Em 2077, o único trabalho restante será _.",
			"O que acabou de estragar minha apresentação? _.",
			"Nada diz 'família brasileira' como _.",
			"Por que estou acordado às 4h da manhã? _.",
			"O próximo grande sucesso do streaming: _ com _.",
			"Qual é o segredo de uma vida longa? _.",
			"O prefeito prometeu acabar com _.",
			"Minha terapia está indo bem, exceto por _.",
			"Em vez de currículo, minha empresa agora exige _.",
			"A fofoca do escritório hoje é sobre _.",
			"O que tem no churrasco do meu tio? _.",
			"Cientistas descobriram que _ cura ressaca.",
			"O que estragou meu fim de semana? _ e _.",
			"Depois de anos, finalmente descobriram o que tem dentro de _.",
			"O segredo do meu bolo é _, mas ninguém precisa saber.",
			"O que me fez ser demitido? _.",
			"A novela das nove desta vez é sobre _.",
			"O que tem dentro da mala do meu pai? _.",
			"Neste Natal, vou presentear todos com _.",
			"O novo plim plim da televisão é _.",
			"Quando tudo der errado, ainda resta _.",
			"Minha maior fraqueza na entrevista de emprego? _.",
		},
	})
}