package decks

// Dev & TI: o deck para quem trabalha com software. Deploy de
// sexta-feira, planilha que é o sistema de verdade, estagiário com
// acesso de admin -- dor de programador em formato de carta.
func init() {
	Register(Deck{
		ID:          "dev",
		Name:        "Dev & TI",
		Emoji:       "💻",
		Description: "Deploy de sexta, planilha que é o sistema e bug que some quando o gerente olha.",
		whites: []string{
			"Um deploy de sexta-feira às 18h",
			"O bug que some quando o gerente olha",
			"Um comentário TODO de 2019",
			"Um merge conflict de quatrocentos arquivos",
			"O 'funciona na minha máquina'",
			"Café no lugar de documentação",
			"Um cron job das 3h que ninguém sabe o que faz",
			"A base de dados sem backup",
			"Uma migração de banco que destruiu a produção",
			"O estagiário com acesso de admin",
			"Um alerta às 4h da manhã",
			"Git blame apontando pra mim",
			"Um microserviço que chama outro microserviço",
			"A planilha Excel que é o sistema de verdade",
			"Uma SQL injection na API de cadastro",
			"O 'só mais uma coisinha' do gerente",
			"Uma reunião com doze pessoas e zero decisão",
			"O hotfix que virou feature",
			"Trzentos story points atrasados no Jira",
			"Senha compartilhada no WhatsApp do time",
			"O code review que só diz 'LGTM'",
			"Uma branch protegida por 'confia'",
			"O notebook que só compila dentro do trabalho",
			"Um pull request de duas mil linhas",
			"Node_modules mais pesado que o projeto",
			"A reunião que podia ser um e-mail",
			"Um certificado SSL vencido numa segunda-feira",
			"O 'é só um ajuste rápido' do cliente",
			"Código de Stack Overflow copiado sem entender",
			"Um teste unitário que não testa nada",
			"O token de produção commitado",
			"Um feedback de performance: 'você precisa melhorar'",
			"O cliente que 'tem pressa' desde março",
			"Um servidor rodando na conta pessoal do estagiário",
			"A documentação que só diz 'ver código'",
			"Um deadline 'para ontem'",
			"O bug de fuso horário",
			"Uma feature que ninguém usa",
			"O 'não era pra isso ter ido pra produção'",
			"Um alerta silenciado há semanas",
			"O 'vou dar uma olhada' do sênior",
			"Uma ferramenta nova de produtividade obrigatória",
		},
		blacks: []string{
			"A pior coisa que pode acontecer num deploy de sexta-feira: _.",
			"A produção caiu. O log aponta para _.",
			"O que o estagiário commitou direto na main? _.",
			"Nossa arquitetura agora depende totalmente de _.",
			"A retrospectiva durou quatro horas por causa de _.",
			"O que a planilha Excel faz melhor que qualquer sistema? _.",
			"O cliente abriu um ticket urgente sobre _.",
			"O que deixou o gerente feliz e a equipe em pânico? _.",
			"Na próxima sprint, vamos priorizar _.",
			"O incidente de produção foi causado por _ e agravado por _.",
			"O que está escrito no commit 'fix' de hoje? _.",
			"O novo CTO anunciou que vamos migrar tudo para _.",
		},
	})
}