package decks

// O Pesadão: o deck "super pesado" -- humor negro sem freio. Morte,
// crime, drogas, tabus e a existência como um todo, sempre no registro
// do absurdo. O mesmo contrato de conteúdo do pacote: nada de xingamento
// contra grupo, nada de menor sexualizado, ninguém real citado -- o
// peso vem da morte, do azar e da falta de esperança, não de ódio.
func init() {
	Register(Deck{
		ID:          "pesadao",
		Name:        "Pesadão",
		Emoji:       "💀",
		Description: "Humor negro sem freio: morte, crime e azar. Ative por sua conta e risco.",
		whites: []string{
			"O velório do meu tio com open bar",
			"A última vontade do defunto",
			"Desconto de 70% em urnas funerárias",
			"O embalsamador mais barato da cidade",
			"Ressaca de três dias com gim barato",
			"O testamento que esqueci de atualizar",
			"Um atestado de óbito com erro de português",
			"Cremar o patrimônio da família",
			"O cheiro de formol",
			"Um assaltante com pavor de cachorro",
			"A fuga da cadeia pelo ralo da privada",
			"A encomenda esquecida do caminhão de farinha",
			"Um porre de caixa dois",
			"O testemunho falso no tribunal do júri",
			"A ficha criminal do tio que 'deu erro no sistema'",
			"Meu ex aparecendo no meu velório fingindo que sentiu falta",
			"O capanga aposentado virando Uber",
			"A dívida do jogo do bicho",
			"Cachorro caramelo achando o corpo enterrado no quintal",
			"A cena do crime mal lavada",
			"Um anjo da morte com pressa de terminar o turno",
			"O luto de quatro dias que a CLT dá",
			"Chorar no espelho vestindo a calça do meu falecido pai",
			"O inventário que dura mais que o luto",
			"Uma herança que vale menos que o imposto",
			"O coveiro pedindo gorjeta",
			"Um enterro de gato no quintal do vizinho",
			"A seringa na areia depois do réveillon",
			"Uma cartela de bingo no asilo",
			"O idoso que venceu a maratona por desistência geral",
			"Um caixão que não fecha direito",
			"O 'posso entrar?' da Morte no meio da reunião",
			"Um espírito preguiçoso que não assombra ninguém",
			"A missa de sétimo dia com caixa de som Bluetooth",
			"O remédio vencido desde 2009",
			"Um transplante de rim pago em doze parcelas",
			"A ambulância que só chega depois",
			"O plano de saúde que nega tudo",
			"Uma urna funerária com adesivo do time de futebol",
			"O bolo de funeral escrito 'Parabéns'",
			"Um velório transmitido ao vivo com legendas",
			"O 'eu sinto muito' automático do RH",
			"A última refeição do condenado: um x-tudo",
			"O pneu queimando na rua",
			"Um cofre cheio de dinheiro falso",
			"O bandido que só assalta quem merece",
			"A testemunha que viu tudo e preferiu calar",
			"Um jantar de réquiem com macarrão instantâneo",
			"A lápide com QR code",
			"Meu espírito zoeiro rondando a casa dos meus inimigos",
			"O pânico de segunda-feira às 6h50",
			"Um atestado de sanidade assinado por quem assinou o meu empréstimo",
			"O 'não resiste' do médico com cara de tédio",
			"Uma vala comum lotada",
			"O fiador que sumiu da Justiça",
			"A dívida que sobrevive ao falecido",
			"Um enterro marcado no mesmo dia da final do campeonato",
			"O canibal que virou vegetariano por ética",
			"Comer o falecido para não desperdiçar",
			"O sequestrador pedindo resgate em Pix",
			"A cova rasa com o nome errado na lápide",
			"O lixo hospitalar vendido como brinquedo",
			"A cadeira elétrica artesanal",
			"O carrasco aposentado dando aula de educação física",
			"O transplante de córnea do doador errado",
			"A doença rara que só eu tenho e ninguém acredita",
			"O exumado voltando só para reclamar do caixão",
			"O fantasma cobrando aluguel atrasado",
			"A mão decepada no maquinário do tio",
			"O cemitério de animais com nota fiscal",
			"Meu plano de saúde cobrindo só o velório",
			"O esqueleto no armário virando decoração de Halloween",
			"A panela de pressão sem válvula",
			"O freio de mão esquecido na ladeira errada",
			"A aposta de quem morre primeiro",
			"O velório com open bar pago pelo seguro de vida",
			"A herança disputada por quem nem foi ao enterro",
			"__",
			"__",
		},
		blacks: []string{
			"O que está escrito na minha lápide? 'Aqui jaz quem morreu de _.'",
			"O velório foi interrompido por _.",
			"Cientistas confirmaram: a verdadeira causa de morte do brasileiro é _.",
			"No meu enterro, em vez de flores, peço que jogem _ na cova.",
			"O que a polícia encontrou no porta-malas? _.",
			"Meu plano de aposentadoria: _ até os 60, depois _.",
			"O que transformou um churrasco tranquilo numa tragédia? _.",
			"A autópsia revelou a verdade: _.",
			"Nada diz 'boa sorte no primeiro dia de trabalho' como _.",
			"A última coisa que passou pela minha cabeça antes do acidente foi _.",
			"O que o médico não deveria ter dito durante a cirurgia? _.",
			"O bandido entrou na casa e levou apenas _.",
			"Minha herança vai ser dividida entre _ e _.",
			"O que fez o velório ficar mais animado que a festa? _.",
			"No inferno, a punição eterna é _ ao lado de _.",
			"A polícia perguntou onde eu estava naquela noite. Eu disse: _.",
			"O que acabou de cair da ambulância? _.",
			"Meu último desejo: _.",
			"O que fez o coveiro pedir demissão? _.",
			"A última coisa que o defunto disse antes de apagar foi _.",
			"Em vez de cadeia, o juiz sentenciou o réu a _ para sempre.",
			"O que aparece no raio-x do meu estômago? _.",
			"Meu terapeuta desistiu de mim quando falei sobre _.",
			"O fim do mundo não veio por meteorito: veio por _.",
		},
	})
}