package decks

// O Pesadão Master: a versão sem freio nenhum.
// Foco: humor negro, tabus morais, religião, profanação e desgraça humana
// em frases curtas. Contrato mantido: nada de grupo como alvo de ódio,
// nada de menor sexualizado, ninguém real citado — o peso vem do morbo,
// da fé vendida e da morte burocrática.
func init() {
	Register(Deck{
		ID:          "pesadao_master",
		Name:        "Pesadão (Edição Definitiva)",
		Emoji:       "💀",
		Description: "O fundo do poço sem rodeios: religião, tabu, cadáver e desesperança. Textos curtos e diretos.",
		whites: []string{
			// --- Aborto, Parto & Família ---
			"Um feto num pote de vidro",
			"O feto que caiu na privada",
			"O kit de aborto do Mercado Livre",
			"Remédio abortivo vencido",
			"Chá de revelação que incendiou o matagal",
			"O ultrassom que deu errado",
			"Vender o cordão umbilical no OLX",
			"A barriga de aluguel com parcelas atrasadas",
			"O parto no banco de trás do busão lotado",
			"A parteira que só aceita Pix",
			"Mamadeira com cachaça",
			"O berço de segunda mão cheio de baratas",
			"Mãe que esqueceu o bebê no carro",
			"Pai que foi comprar cigarro em 1994",
			"Adotar criança só pra sacar o auxílio",
			"A seita que proíbe transfusão de sangue pro recém-nascido",
			"A vasectomia com alicate",
			"Camisinha furada de propósito",
			"Pílula do dia seguinte com Guaraná Jesus",
			"O teste de DNA ao vivo no programa de auditório",
			"A herança disputada antes do último suspiro",

			// --- Religião, Crença & Heresia ---
			"Santo Sudário como pano de chão",
			"Hóstia recheada de maconha",
			"Cocaína escondida na imagem de Nossa Senhora",
			"Bíblia usada como seda de baseado",
			"Vinho da missa trocado por Corote",
			"O dízimo pago com sexo",
			"O pastor lavando o dízimo no motel",
			"O pastor pego no vestiário com o coroinha adulto",
			"Água benta como lubrificante",
			"O terço na função errada",
			"Dildo feito da madeira da cruz",
			"O papa vendo pornô no celular durante a missa",
			"A freira vendendo foto do pé no privado",
			"Exorcismo com extintor de incêndio",
			"Batismo por imersão no esgoto",
			"A seita que marcou o suicídio coletivo pro dia depois do pagamento",
			"O exorcista cobrando hora extra",
			"A clínica de cura gay que aceita Pix e nunca devolve",
			"O pastor que cura câncer e fatura o estacionamento",
			"A imagem do santo que chorou óleo de fritura",
			"Relíquia do dedo do santo à venda no Mercado Livre",
			"Milagre com nota fiscal e garantia de 90 dias",
			"Água benta com prazo de validade",
			"A missão vendendo kit de DNA de santo",
			"Confissão por áudio no WhatsApp",
			"O padre cobrando a missa em 12x no cartão",
			"O coroinha apostando no resultado do exorcismo",
			"A horda de crentes tentando expulsar o demônio do autista",
			"A novena pra defunto passar no céu sem fiscalização",
			"O santo canonizado por engano",
			"A exumação do santo pra conferir se tá cheiroso",
			"Deus com a caixa de entrada lotada",
			"Deus te deixando no aguardando atendimento",
			"A oração respondida com 'usuário não encontrado'",
			"O profeta que erra a profecia e remarca a data",
			"Sacrifício de bode na esquina",
			"O açougue atendendo a seita em horário especial",
			"A hóstia substituída por Doritos",
			"O padre que esqueceu o microfone ligado no banheiro",
			"O féretro do santo transformado em caixa de som",
			"Crucifixo de porta-guardanapo",
			"Dízimo parcelado com juros",
			"A visita de domingo às 7h com a revista na mão",

			// --- Hipocrisia, Tabu & Crime ---
			"O homofóbico pego no flagra na sauna",
			"O homofóbico com o histórico do navegador aberto",
			"O 'não tenho nada contra, mas...'",
			"O deputado 'família cristã' e a diária do motel",
			"O pregador antivício apostando no jogo do bicho",
			"O 'ex-gay' que recaiu no segundo culto",
			"O nazista que mora com a mãe",
			"O idoso do Zap reivindicando a ditadura",
			"A família batendo palma pro áudio sobre a ditadura",
			"Sauna masculina às 16h de terça",
			"Flagrante no banheiro da balada",
			"Incesto por falta de opção",
			"Necrofilia interrompida porque o corpo espirrou",
			"Mendigo expulso da porta da igreja",
			"Atropelar e seguir direto pra final",
			"Vender rim pra pagar o boleto do rim",
			"Roubo de dente de ouro no necrotério",
			"A cova rasa no quintal do tio",
			"Sequestro com cobrança via Pix",
			"O vizinho fofoqueiro morrendo engasgado",
			"O camburão com direção assistida",
			"A vala comum com planta baixa",
			"O açougue que não pergunta de onde vem a carne",

			// --- Morte, Acidente & Desgraça ---
			"O velório com open bar",
			"Cremar o parente errado duas vezes",
			"O forno crematório em horário de pico",
			"A funerária alugando o mesmo caixão três vezes por semana",
			"Comer o falecido pra não desperdiçar",
			"Remédio tarja preta com cerveja",
			"A enfermeira desligando o aparelho pra carregar o celular",
			"Gaze esquecida dentro da barriga",
			"A cirurgia costurada com nylon de pesca",
			"Transplante clandestino de córnea",
			"O 'não resistiu' dito bocejando",
			"Lixo hospitalar despejado no rio da cidade",
			"O velório no TikTok com patrocínio de marca",
			"A lápide com QR Code pro Pix da dívida",
			"Teste de HIV positivo no Dia dos Namorados",
			"A mão decepada no maquinário do tio",
			"O eutanasiador autônomo com plano mensal",
			"Panela de pressão sem válvula",
			"Freio de mão esquecido na ladeira do cemitério",
			"Atestado de óbito com erro de português",
			"Chorar trancado no banheiro da firma",
			"Overdose de vermífugo",
			"Gente morta na fila do SUS",
			"O enterro no dia da final do campeonato",
			"O coveiro pedindo gorjeta",
			"Autópsia feita sem luva",
			"O idoso caído há duas semanas",
			"O inquilino morto que continuou pagando aluguel em débito automático",
			"O nicho do cemitério sublocado pra dois",
			"O cemitério reciclando as lápides antigas",

			// --- Miserabilidade & Existencialismo ---
			"O pânico de segunda-feira às 6h",
			"A dívida do jogo do bicho",
			"O luto de 4 dias da CLT",
			"Ser despejado no próprio aniversário",
			"O seguro de vida que cobre só o caixão usado",
			"Fazer fiado no puteiro",
			"A marmita azeda na firma",
			"Cair no golpe do bilhete premiado",
			"A herança que é só dívida",
			"O plano de saúde que sugere eutanásia",
			"A aposentadoria que chega junto com o laudo",
			"O médico dando garantia de cinco anos",
			"O céu lotado e você na lista de espera",
			"A vida que vale menos que o caixão",
			"__",
			"__",
		},
		blacks: []string{
			"O que o padre encontrou debaixo do altar? _.",
			"O que tem dentro do pote de maionese no porão? _.",
			"O que a lavanderia do convento se recusa a lavar? _.",
			"O que fez o bispo transferir o padre de madrugada? _.",
			"O que a diocese preferiu não investigar? _.",
			"O que estava no envelope grosso entregue ao bispo? _.",
			"O pastor prometeu que a oferta cura até _.",
			"O que o pastor fez com o dízimo do mês? _.",
			"O que caiu da bolsa da freira na hora da comunhão? _.",
			"O milagre da semana foi transformar _ em _.",
			"Em vez de água benta, o padre usou _.",
			"O que ficou de fora do laudo do necrotério? _.",
			"O que fez o cemitério lacrar os portões? _.",
			"O que a família achou ao abrir o caixão do vovô? _.",
			"O bilhete dentro do caixão dizia apenas: _.",
			"O que o cachorro caramelo trouxe de volta? _.",
			"O que fez a funerária cobrar taxa de urgência? _.",
			"O que a diarista achou embaixo da cama? _.",
			"O que o vizinho ouviu atravessando a parede? _.",
			"O que fez o velório virar briga generalizada? _.",
			"A briga da ceia de Natal começou com _.",
			"O motivo do divórcio dos meus pais foi _.",
			"O que a polícia encontrou no porta-malas do bispo? _.",
			"O teste de DNA ao vivo provou que o pai do bebê é _.",
			"O que a fofoqueira da rua viu pela janela? _.",
			"O que está escrito na minha lápide? '_'.",
			"Qual é o novo sacrifício exigido pela seita? _.",
			"O que o coroinha vendeu pro mercado negro? _.",
			"O que fez o anjo pedir demissão? _.",
			"O que Deus mandou direto pro spam? _.",
			"O que fez o demônio pedir transferência? _.",
			"O que a escola pediu pra não avisar aos pais? _.",
			"O que o médico disse antes de desligar os aparelhos? '_'.",
			"A autópsia revelou que a verdadeira causa da morte foi _.",
			"No meu enterro, em vez de flores, quero _.",
			"O que o estagiário esqueceu dentro do paciente? _.",
			"A causa da demissão do coveiro foi _.",
			"O que fez a prefeitura interditar o velório? _.",
			"A única coisa pior do que a morte é _.",
		},
	})
}
