package decks

// Treta & Amor: relacionamentos, apps de namoro, sogra, visto azul e
// as conversas que ninguém quer ter. Cru, mas no campo da zoeira --
// nada explícito, ninguém real.
func init() {
	Register(Deck{
		ID:          "treta",
		Name:        "Treta & Amor",
		Emoji:       "💔",
		Description: "Visto azul, sogra, ex e as conversas que ninguém quer ter.",
		whites: []string{
			"Um 'visto' azul sem resposta",
			"O ex que aparece no aniversário",
			"Um match que nunca respondeu",
			"Ciúmes do cachorro",
			"O 'estamos bem' que não está",
			"Uma discussão sobre algo de 2018",
			"Sair para 'só uma cerveja' com o ex",
			"O 'eu não sou ciumento, mas'",
			"Um date no McDonald's",
			"Fingir dormir na frente da sogra",
			"O perfil no app com foto de 2015",
			"Um 'me esquece' seguido de 'oi'",
			"A cunhada que cozinha melhor que você",
			"O 'saindo com as amigas' às 23h50",
			"Um noivo que perde a aliança",
			"O 'tô bem' furioso",
			"Ficar de olho no stories do crush",
			"Um término por áudio",
			"O 'a gente precisa conversar'",
			"Um casamento marcado para dezembro com tudo pago",
			"O 'ele é só um amigo'",
			"Um cheiro de perfume estranho no carro",
			"A mãe que entra sem bater",
			"Um date que só fala de si mesmo",
			"O 'sua mãe é muito legal' com cara fechada",
			"Receber 'podemos conversar?' depois de semanas",
			"Um 'me dá um tempo' de três meses",
			"O 'eu sabia que isso ia acontecer'",
			"Uma segunda chance de número sete",
			"O 'não estava vendo seu perfil, caiu por acaso'",
			"Um casal se beijando na fila do banco",
			"O 'me responde rápido' de segunda-feira",
			"Um date que só fala do ex",
			"O 'tudo bem' com ponto final",
			"Um 'bom dia' com três corações e um 'tchau' seco",
			"O 'tô saindo' que era com outra pessoa",
			"Uma amizade que virou treta por fofoca",
			"O 'você mudou muito'",
			"Um 'amo você' dito no automático",
			"A sogra que comenta todas as suas fotos",
			"Um presente de 'quebra-galho' comprado no posto",
			"O 'posso ir junto?' na balada dos amigos",
		},
		blacks: []string{
			"O que encerrou meu namoro de oito anos? _.",
			"A conversa difícil de hoje vai ser sobre _.",
			"No terceiro encontro, descobri que meu date coleciona _.",
			"O que o 'visto' azul esconde? _.",
			"Meu casamento quase acabou por causa de _.",
			"O que o app de namoro me recomendou hoje? _.",
			"A treta da família no Natal começou com _.",
			"O que a sogra disse que nunca vai ser esquecido? _.",
			"Meu date terminou quando o garçom trouxe _.",
			"O que eu descobri no celular do meu parceiro? _.",
			"O que 'a gente precisa conversar' realmente significa? _.",
			"Nada diz 'eu ainda gosto de você' como _.",
			"O grupo da família explodiu porque alguém postou _.",
			"O que acabou com a amizade de vinte anos? _.",
		},
	})
}