x-arcane:
  urls:
    - https://ntfy.sh

services:
  ntfy:
    image: binwiederhier/ntfy:${NTFY_VERSION:-latest}
    restart: unless-stopped
    command: serve
    ports:
      - "${APP_PORT:-8090}:80"
    environment:
      TZ: ${TZ:-UTC}
    volumes:
      - ntfy-cache:/var/cache/ntfy
      - ntfy-data:/etc/ntfy

volumes:
  ntfy-cache:
  ntfy-data:
