import { useEffect, useRef } from "react";
import lottie, { type AnimationItem } from "lottie-web";

// The raw-Lottie counterpart of AnimatedIcon: AnimatedIcon rides
// react-useanimations' icon presets, while this one takes any
// animationData -- which is what the room's bonequinhos are (custom
// character JSONs generated by scripts/generate-avatars.mjs, not
// presets). Same conventions as its sibling: a pixel size, inline-flex
// so it drops into a text row without stretching it, and one lottie-web
// player per instance destroyed on unmount.
export function Lottie({
  animationData,
  size = 28,
  loop = true,
  autoplay = true,
  speed = 1,
  className,
  title,
}: {
  animationData: unknown;
  size?: number;
  loop?: boolean;
  autoplay?: boolean;
  speed?: number;
  className?: string;
  // Screen-reader label; the characters are decorative in most spots,
  // so it's optional and omitted means aria-hidden.
  title?: string;
}) {
  const hostRef = useRef<HTMLDivElement>(null);
  const animRef = useRef<AnimationItem | null>(null);

  useEffect(() => {
    if (!hostRef.current) return;
    const anim = lottie.loadAnimation({
      container: hostRef.current,
      renderer: "svg",
      loop,
      autoplay,
      animationData: animationData as object,
    });
    anim.setSpeed(speed);
    animRef.current = anim;
    return () => anim.destroy();
    // animationData is a static import per character -- it never changes
    // for a mounted player, so it's deliberately not a dependency here.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loop, autoplay, speed]);

  return (
    <div
      ref={hostRef}
      role={title ? "img" : undefined}
      aria-label={title}
      aria-hidden={title ? undefined : true}
      className={className}
      style={{ width: size, height: size, display: "inline-flex", flexShrink: 0 }}
    />
  );
}