variable "image_version" {
  description = "sknnr/project-zomboid-server:<version> image tag."
  type        = string
  default     = "latest"
}

variable "server_name" {
  description = "Name shown in the in-game server browser / co-op list."
  type        = string
  default     = "MeuServidorZomboid"
}

variable "server_password" {
  description = "Join password players must type in-game to connect. Generated by root secrets.tf and seeded into Vaultwarden."
  type        = string
  sensitive   = true
}

variable "admin_username" {
  description = "In-game admin login, used with admin commands (grantadmin etc.)."
  type        = string
  default     = "admin"
}

variable "admin_password" {
  description = "Password for var.admin_username's in-game admin login. Generated by root secrets.tf and seeded into Vaultwarden."
  type        = string
  sensitive   = true
}

variable "max_players" {
  description = "Simultaneous player slots the server accepts."
  type        = number
  default     = 10
}
